name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      run: echo ::set-output name=tag::$(echo date +%s)
    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag bus-poller:${{steps.vars.outputs.tag}} --tag bus-poller:latest
    - name: Push the image with version number
      run: docker push bus-poller:${{steps.vars.outputs.tag}}
    - name: Push the latest image
      run: docker push bus-poller:tag
