name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag trtd/bus-poller:${GITHUB_RUN_NUMBER} --tag trtd/bus-poller:latest
    - name: Push the image with version number
      run: docker push trtd/bus-poller:${GITHUB_RUN_NUMBER}
    - name: Push the latest image
      run: docker push trtd/bus-poller:latest
